import React, { useRef, useState } from 'react';
import CephalogramCanvas from '../components/CephalogramCanvas';
import { exportToPDF } from '../utils/exportPdf';
import { Download, ArrowLeft, Activity, Info } from 'lucide-react';

const ResultPage = ({ imageSrc, results, onBack }) => {
  const [isExporting, setIsExporting] = useState(false);
  const reportRef = useRef(null);

  const { landmarks, measurements } = results;

  const handleExport = async () => {
    setIsExporting(true);
    await exportToPDF('report-container');
    setIsExporting(false);
  };

  return (
    <div className="max-w-[1400px] mx-auto p-4 sm:p-6 lg:p-8 animate-fade-in">
      {/* Header Actions */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8 gap-4">
        <button
          onClick={onBack}
          className="flex items-center text-slate-500 hover:text-primary transition-colors font-medium bg-white px-4 py-2 rounded-lg shadow-sm border border-slate-200"
        >
          <ArrowLeft className="w-5 h-5 mr-2" />
          Upload New Image
        </button>
        
        <div className="flex items-center gap-3">
          <button
            onClick={handleExport}
            disabled={isExporting}
            className={`flex items-center px-6 py-3 rounded-lg font-bold text-white transition-all shadow-md
              ${isExporting ? 'bg-primary/70 cursor-wait' : 'bg-primary hover:bg-primary/90 hover:shadow-lg hover:-translate-y-0.5'}
            `}
          >
            <Download className="w-5 h-5 mr-2" />
            {isExporting ? 'Generating PDF...' : 'Export PDF Report'}
          </button>
        </div>
      </div>

      {/* Main Content Area to Export */}
      <div id="report-container" className="bg-white rounded-2xl shadow-xl border border-slate-100 overflow-hidden" ref={reportRef}>
        
        {/* Report Header for PDF */}
        <div className="bg-slate-50 p-6 border-b border-slate-100 mb-6 flex justify-between items-center">
          <div>
            <h2 className="text-2xl font-bold text-slate-800 flex items-center">
              <Activity className="w-6 h-6 mr-3 text-primary" />
              Cephalometric Analysis Report
            </h2>
            <p className="text-slate-500 mt-1">Generated by Digital Orthodontic AI</p>
          </div>
          <div className="text-right text-sm text-slate-400">
            {new Date().toLocaleDateString()}
          </div>
        </div>

        <div className="p-6 pt-0 flex flex-col lg:flex-row gap-8">
          {/* Left Canvas Area (Landscape oriented image) */}
          <div className="flex-1 min-h-[500px] lg:min-h-[600px] bg-slate-50 rounded-xl flex items-center justify-center p-2 border border-slate-200">
            <CephalogramCanvas imageSrc={imageSrc} landmarks={landmarks} />
          </div>

          {/* Right Data Area */}
          <div className="w-full lg:w-[450px] xl:w-[500px] flex flex-col gap-6">
            
            {/* Summary Card */}
            <div className="bg-primary/5 rounded-xl p-6 border border-primary/10">
              <h3 className="text-lg font-bold text-primary mb-2 flex items-center">
                <Info className="w-5 h-5 mr-2" />
                Analysis Summary
              </h3>
              <p className="text-slate-600 text-sm leading-relaxed">
                29 landmarks successfully detected on the lateral cephalogram.
                The structural measurements and angular analyses are normalized against standard cephalometric norms.
              </p>
            </div>

            {/* Diagnostics Table */}
            <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
              <div className="bg-slate-50 px-5 py-4 border-b border-slate-200">
                <h3 className="font-bold text-slate-800">Skeletal Measurements</h3>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full text-left text-sm whitespace-nowrap">
                  <thead className="bg-slate-50/50 text-slate-500 uppercase text-xs">
                    <tr>
                      <th className="px-5 py-3 font-semibold">Measurement</th>
                      <th className="px-5 py-3 font-semibold">Patient</th>
                      <th className="px-5 py-3 font-semibold text-center">Norm</th>
                      <th className="px-5 py-3 font-semibold text-center">Status</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    {measurements.map((item, idx) => (
                      <tr key={idx} className="hover:bg-slate-50/50 transition-colors">
                        <td className="px-5 py-4 font-medium text-slate-700">{item.name}</td>
                        <td className="px-5 py-4 font-bold text-slate-900">{item.value}°</td>
                        <td className="px-5 py-4 text-slate-500 text-center">{item.normal}</td>
                        <td className="px-5 py-4 text-center">
                          <span className={`inline-flex px-3 py-1 rounded-full text-xs font-bold ${
                            item.status === 'Normal' 
                              ? 'bg-green-100 text-green-700' 
                              : 'bg-red-100 text-red-700'
                          }`}>
                            {item.status}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
            
            {/* Add more tables or metrics here theoretically */}

          </div>
        </div>
      </div>
    </div>
  );
};

export default ResultPage;
